#!/usr/bin/env bash
set -euo pipefail

# SAIA Models Sync Script for opencode-saia-plugin
# Fetches latest models from SAIA API and updates opencode.json
# Run this periodically to keep the plugin in sync with SAIA

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$PLUGIN_DIR/opencode.json"
TEMP_MODELS="$PLUGIN_DIR/.tmp-saia-models.json"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
print_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# API configuration
SAIA_API_KEY="${SAIA_API_KEY:-}"
API_BASE_URL="${SAIA_API_URL:-https://chat-ai.academiccloud.de/v1}"

# Check for API key
if [[ -z "$SAIA_API_KEY" ]]; then
    print_error "SAIA_API_KEY environment variable not set"
    print_info "Set it with: export SAIA_API_KEY=your_key"
    exit 1
fi

print_info "Fetching latest SAIA models from $API_BASE_URL..."

# Fetch models from API
MODELS_JSON=$(curl -s --max-time 30 "$API_BASE_URL/models" \
    -H "Authorization: Bearer $SAIA_API_KEY")

if [[ -z "$MODELS_JSON" ]] || ! echo "$MODELS_JSON" | jq -e '.data' >/dev/null 2>&1; then
    print_error "Failed to fetch models from SAIA API"
    print_info "Response: $MODELS_JSON"
    exit 1
fi

MODEL_COUNT=$(echo "$MODELS_JSON" | jq -r '.data | length')
print_info "Found $MODEL_COUNT models from SAIA API"

# ── Facts vs taste ────────────────────────────────────────────────────────────
# Facts (context window, reasoning support, modalities, display names, vendor
# recommended sampling) live in data/saia-models.json, generated by merging the
# live SAIA API + the GWDG docs table + scripts/reasoning-models.json:
#     node scripts/collect-saia-model-info.mjs
# Only output limits, cost/latency estimates, categories and aliases below are
# opinion. Unknown models get sane defaults instead of being skipped.
DATA_FILE="$PLUGIN_DIR/data/saia-models.json"

if command -v node >/dev/null 2>&1 && node "$SCRIPT_DIR/collect-saia-model-info.mjs" --out "$DATA_FILE"; then
    print_info "Refreshed data/saia-models.json (live API + GWDG docs)"
elif [[ -f "$DATA_FILE" ]]; then
    print_warn "Collector unavailable — using committed data/saia-models.json"
else
    print_error "No data/saia-models.json and collector failed"
    exit 1
fi

# fact_for <model-id> <jq expr over one model object>  (prints "null" if absent)
fact_for() {
    jq -cr --arg id "$1" \
        "first(.models[] | select(.id == \$id) | $2) // \"null\"" "$DATA_FILE"
}

# Taste: output limits + cost/latency estimates (id|output_tokens|cost_per_1k|latency)
TASTE=(
    "apertus-70b-instruct-2509|8192|0.025|slow"
    "deepseek-v4-flash-0731|32768|0.008|fast"
    "devstral-2-123b-instruct-2512|16384|0.075|slow"
    "gemma-4-31b-it|8192|0.012|moderate"
    "glm-5.3-flash|32768|0.015|fast"
    "meta-llama-3.1-8b-instruct|4096|0.003|fast"
    "mistral-medium-3.5-128b|8192|0.075|slow"
    "openai-gpt-oss-120b|8192|0.075|slow"
    "qwen3-30b-a3b-instruct-2507|16384|0.018|moderate"
    "qwen3-coder-next|16384|0.015|fast"
    "qwen3-omni-30b-a3b-instruct|4096|0.018|moderate"
    "qwen3.5-397b-a17b|32768|0.125|very-slow"
    "qwen3.6-35b-a3b|16384|0.018|moderate"
    "qwen3.8-27b|32768|0.006|moderate"
)
TASTE_DEFAULT="16384|0.05|moderate"  # new/unknown SAIA models: sane defaults

taste_for() {
    local want="$1" row
    for row in "${TASTE[@]}"; do
        [[ "$row" == "${want}|"* ]] && { printf '%s' "${row#*|}"; return 0; }
    done
    printf '%s' "$TASTE_DEFAULT"
}

# Aliases
#
# Read from src/saia-aliases.mjs — the same map the runtime plugin uses — so the
# checked-in config and the plugin can never promise different shortcuts.
ALIASES=()
if command -v node >/dev/null 2>&1; then
    while IFS= read -r alias_row; do
        [ -n "$alias_row" ] && ALIASES+=("$alias_row")
    done < <(node -e "import('$PLUGIN_DIR/src/saia-aliases.mjs').then((m) => console.log(m.saiaAliasRows().join('\\n')))" 2>/dev/null)
fi
if [ "${#ALIASES[@]}" -eq 0 ]; then
    print_warn "Could not read the alias map from src/saia-aliases.mjs (is node available?)"
fi

# Categorize model based on ID
categorize() {
    local id="$1"
    case "$id" in
        *thinking*|*r1*|qwen3.5-*|qwen3.6-35b-a3b|qwen3.8-27b)
            echo "reasoning"
            ;;
        *coder*)
            echo "coder"
            ;;
        *omni*|*vl-*|*vision*|internvl*)
            echo "vision"
            ;;
        devstral*|mistral-medium*|glm-5.3-flash)
            echo "agentic"
            ;;
        *120b|*128b|*235b|*675b)
            echo "large-context"
            ;;
        *)
            echo "general"
            ;;
    esac
}

# Get timestamp
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Build the new model list
print_info "Generating opencode.json..."

# Get list of API model IDs
API_MODEL_IDS=$(echo "$MODELS_JSON" | jq -r '.data[].id' | sort)
FINAL_MODELS="$API_MODEL_IDS"

# Initialize empty models JSON
echo "{}" > "$TEMP_MODELS"

# Process all models
echo "$FINAL_MODELS" | while read -r model_id; do
    [[ -z "$model_id" ]] && continue
    
    context=$(fact_for "$model_id" '.context_window.tokens')
    if [[ "$context" == "null" ]]; then
        print_warn "No context-window facts for $model_id (skipping — update GWDG docs or the collector)"
        continue
    fi
    description=$(fact_for "$model_id" '.name + " (SAIA)"')
    reasoning=$(fact_for "$model_id" '.reasoning.supported == true | tostring')
    input_types=$(echo "$MODELS_JSON" | jq -r --arg id "$model_id" 'first(.data[] | select(.id == $id) | .input // ["text"]) | join(",")')
    recommended=$(fact_for "$model_id" '.recommended')
    IFS='|' read -r max_tokens cost latency <<< "$(taste_for "$model_id")"
    # never advertise an output cap larger than the model's context
    if [ "$context" != "null" ] && [ "$max_tokens" -gt "$context" ] 2>/dev/null; then
        max_tokens="$context"
    fi
    category=$(categorize "$model_id")
    
    # Format input types as JSON array
    input_json=$(echo "$input_types" | sed 's/,/", "/g' | sed 's/^/["/' | sed 's/$/"]/')
    # OpenCode reads `attachment` (boolean) to decide whether a model can take
    # images/audio/video; an `input` array is silently ignored, which is why vision
    # models looked text-only. See data/saia-models.json for the modalities.
    attachment=$(jq -n --arg types "$input_types" '$types | split(",") | map(select(. != "" and . != "text")) | length > 0')

    # Build model config
    model_config=$(jq -n \
        --arg name "$description" \
        --argjson reasoning "$reasoning" \
        --argjson attachment "$attachment" \
        --argjson context "$context" \
        --argjson max_tokens "$max_tokens" \
        --argjson cost "$cost" \
        --arg latency "$latency" \
        --arg cat "$category" \
        --argjson rec "${recommended:-null}" \
        '{
            name: $name,
            reasoning: $reasoning,
            attachment: $attachment,
            limit: { context: $context, output: $max_tokens },
            metadata: ({
                cost_per_1k_tokens: $cost,
                estimated_latency: $latency,
                category: $cat
            } + (if $rec then {recommended: $rec} else {} end))
        }')
    
    # Add to temp file
    jq --arg id "$model_id" --argjson cfg "$model_config" '. + {($id): $cfg}' "$TEMP_MODELS" > "$TEMP_MODELS.tmp"
    mv "$TEMP_MODELS.tmp" "$TEMP_MODELS"
done

# Add aliases
for alias_row in "${ALIASES[@]}"; do
    alias="${alias_row%%|*}"
    target="${alias_row#*|}"
    
    # Check if target exists in final model list
    if echo "$FINAL_MODELS" | grep -qx "$target"; then
        context=$(fact_for "$target" '.context_window.tokens')
        description=$(fact_for "$target" '.name + " (SAIA)"')
        reasoning=$(fact_for "$target" '.reasoning.supported == true | tostring')
        input_types=$(echo "$MODELS_JSON" | jq -r --arg id "$target" 'first(.data[] | select(.id == $id) | .input // ["text"]) | join(",")')
        recommended=$(fact_for "$target" '.recommended')
        IFS='|' read -r max_tokens cost latency <<< "$(taste_for "$target")"
        if [ "$context" != "null" ] && [ "$max_tokens" -gt "$context" ] 2>/dev/null; then
            max_tokens="$context"
        fi
        category=$(categorize "$target")
        attachment=$(jq -n --arg types "$input_types" '$types | split(",") | map(select(. != "" and . != "text")) | length > 0')
        
        # `id` is the point of an alias: OpenCode asks for the model key unless the
        # entry overrides it, so without `id` SAIA is asked for "best-for-coding" and
        # answers `404 Model Not Found`.
        alias_config=$(jq -n \
            --arg name "$alias → $target" \
            --argjson reasoning "$reasoning" \
            --argjson attachment "$attachment" \
            --argjson context "$context" \
            --argjson max_tokens "$max_tokens" \
            --argjson cost "$cost" \
            --arg latency "$latency" \
            --arg cat "$category" \
            --arg target "$target" \
            --argjson rec "${recommended:-null}" \
            '{
                name: $name,
                reasoning: $reasoning,
                id: $target,
                attachment: $attachment,
                limit: { context: $context, output: $max_tokens },
                metadata: ({
                    cost_per_1k_tokens: $cost,
                    estimated_latency: $latency,
                    category: $cat,
                    alias_of: $target
                } + (if $rec then {recommended: $rec} else {} end))
            }')
        
        jq --arg id "$alias" --argjson cfg "$alias_config" '. + {($id): $cfg}' "$TEMP_MODELS" > "$TEMP_MODELS.tmp"
        mv "$TEMP_MODELS.tmp" "$TEMP_MODELS"
    fi
done

# Read existing opencode.json structure
EXISTING_CONFIG=$(cat "$CONFIG_FILE")

# Update the config file with new models
echo "$EXISTING_CONFIG" | jq --slurpfile models "$TEMP_MODELS" '.provider.saia.models = $models[0]' > "$CONFIG_FILE.tmp"
mv "$CONFIG_FILE.tmp" "$CONFIG_FILE"

# Clean up temp file
rm -f "$TEMP_MODELS"

print_info "✓ Successfully updated $CONFIG_FILE"
print_info "  Models synced: $MODEL_COUNT"
print_info "  Timestamp: $TIMESTAMP"

# Show summary
print_info "Model summary:"
echo "$FINAL_MODELS" | while read -r id; do
    if [[ "$(fact_for "$id" '.context_window.tokens')" != "null" ]]; then
        echo "  ✓ $id"
    else
        echo "  ⚠ $id (no metadata)"
    fi
done
